#ifndef PICALARM_PINOUT_H_
#define PICALARM_PINOUT_H_

#include <xc.h>

//The segments of an LED are defined as such:
//
//  TOP
// T   T
// L   R
//  MID
// B   B
// L   R
//  BOT
#define LED_SEG_LAT       PORTB
#define LED_SEG_TOP       _PORTB_RB3_MASK
#define LED_SEG_TOP_LEFT  _PORTB_RB5_MASK
#define LED_SEG_TOP_RIGHT _PORTB_RB0_MASK
#define LED_SEG_MID       _PORTB_RB7_MASK
#define LED_SEG_BOT_LEFT  _PORTB_RB6_MASK
#define LED_SEG_BOT_RIGHT _PORTB_RB2_MASK
#define LED_SEG_BOT       _PORTB_RB4_MASK

#define LED_SECONDS_INDICATOR    _PORTB_RB1_MASK

#define CATHODE_LAT          PORTC
#define CATHODE_HOURS_TENS   _PORTC_RC7_MASK
#define CATHODE_HOURS_ONES   _PORTC_RC6_MASK
#define CATHODE_MINUTES_TENS _PORTC_RC5_MASK
#define CATHODE_MINUTES_ONES _PORTC_RC4_MASK

#define BUTTON_LAT       PORTA
#define BTN_HOUR         _PORTA_RA3_MASK
#define BTN_MINUTE       _PORTA_RA5_MASK
#define BTN_ALARM_ADJUST _PORTA_RA0_MASK
#define SWT_ALARM        _PORTA_RA1_MASK

#define BUZZER_LAT  PORTA
#define BUZZER_TRIS TRISA
#define BUZZER_PIN  _PORTA_RA5_MASK
#define BUZZER_PPS  RA5PPS

#endif  //PICALARM_PINOUT_H_
